p6/myapp/urls.py
from django.contrib import admin
from django.urls import path
from myapp import views
app_name='myapp'

urlpatterns = [
    path('register/', views.register, name='register')
]

p6/p6/urls.py
from django.contrib import admin
from django.urls import path, include
from myapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('', include('myapp.urls'))
]

p6/myapp/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

def register(request):
    return render(request, 'register.html')

def login(request):
    return render(request, 'login.html')

p6/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}
    {% endblock %}</title>
</head>
<body>
    <h1>Navbar</h1>
    {% block content %}
      
    {% endblock %}
</body>
</html>

p6/templates/index.html
{% extends 'base.html' %}

{% block title %}
Index
{% endblock %}

{% block content %}
<h2>This is from the index.html</h2>
<a href="{% url 'myapp:register' %}">Register</a>
<a href="{% url 'login' %}">Login</a>
{% endblock %}

p6/templates/login.html
{% extends 'base.html' %}

{% block content %}
<a href="{% url 'index' %}">Home</a>
<a href="{% url 'myapp:register' %}">Register</a>
<h2>Login</h2>
{% endblock %} 

p6/templates/register.html
{% extends 'base.html' %}

{% block content %}
<a href="{% url 'login' %}">Login</a>
<h2>Register</h2>
{% endblock %}